#!/bin/sh
#
# Program:      reverse
# Purpose:      Back out the results of a test.
# Author:       G. Pollice, Sun Microsystems
# Notes:        Use this when a test has gone bad because of a problem
#               outside of the actual testing process.
#               This does not do anything with the testlog file.  That has
#               to be done manually.
#
td=`pwd`
if test "`basename $td`" != "TestBed"
then
    echo "$0 must be run in directory TestBed" 1>&2
    exit 1
fi
    
# make sure file needs classification
cd Results/Unclassified
for f in *.Passed
do
    cp $f ../Passed/`basename $f .Passed`
    rm $f `basename $f .Passed`
done
for f in *.Failed
do
    cp $f ../Failed/`basename $f .Failed`
    rm $f `basename $f .Failed`
done
